# Generated by Django 5.2.17 on 2026-08-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('IT & Computers', 'IT & Computers'), ('Networking', 'Networking'), ('Office Supplies', 'Office Supplies'), ('Power', 'Power'), ('Consumables', 'Consumables'), ('Furniture', 'Furniture'), ('Stationery', 'Stationery')], max_length=40)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_points', to='catalog.product')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
