# Generated by Django 5.2.17 on 2026-08-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('initials', models.CharField(max_length=4)),
                ('category', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('badge', models.CharField(choices=[('Verified', 'Verified'), ('Premium', 'Premium'), ('New', 'New'), ('Trusted', 'Trusted')], default='New', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=32, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('color_hex', models.CharField(default='#1a3a5c', max_length=7)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('min_order_qty', models.PositiveIntegerField(default=1)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='catalog.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vendors.vendor')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('vendor', 'product')},
            },
        ),
    ]
