import type {
  Product,
  Vendor,
  VendorListing,
  PriceTrend,
  TickerItem,
  MarketSummary,
  PriceAlert,
  Notification,
} from '@/types';

// ─── Products ─────────────────────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'laptop-hp-840',
    name: 'HP EliteBook 840 G8',
    category: 'IT & Computers',
    subcategory: 'Laptops',
    description: 'Business-grade laptop with Intel Core i5-1135G7, 16GB DDR4, 512GB NVMe SSD. Ideal for corporate procurement.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/HP_Pavilion_dv2000_laptop.jpg/960px-HP_Pavilion_dv2000_laptop.jpg',
    tags: ['Core i5', '16GB RAM', '512GB SSD', 'Windows 11 Pro', '1 year warranty', 'HP'],
    vendorCount: 6,
    bestPrice: 78500,
    avgPrice: 81200,
    worstPrice: 86000,
    priceChange24h: 0.6,
    priceChangePct: 0.6,
    lastUpdated: new Date().toISOString(),
    isFavorited: true,
    hasAlert: false,
    unit: 'per unit',
  },
  {
    id: 'toner-cf230a',
    name: 'HP CF230A Toner Cartridge',
    category: 'Consumables',
    subcategory: 'Toner Cartridges',
    description: 'Original HP black toner cartridge for HP LaserJet Pro M203 and M227. Yields approximately 1,600 pages.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/HP_117A_-_black_laser_toner_cartridge-2407.jpg/960px-HP_117A_-_black_laser_toner_cartridge-2407.jpg',
    tags: ['HP Original', 'Black', '~1,600 pages', 'CF230A', 'LaserJet Pro'],
    vendorCount: 9,
    bestPrice: 3200,
    avgPrice: 3440,
    worstPrice: 3800,
    priceChange24h: -8.0,
    priceChangePct: -8.0,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: true,
    alertPrice: 3000,
    unit: 'per cartridge',
  },
  {
    id: 'cable-cat6-305m',
    name: 'CAT6 Cable (305m box)',
    category: 'Networking',
    subcategory: 'Cables',
    description: 'Outdoor-rated CAT6 UTP stranded cable, 305m box. Suitable for structured cabling in commercial installations.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b8/UTP_Cat_6.jpg',
    tags: ['CAT6', '305m', 'Outdoor rated', 'UTP', 'Stranded'],
    vendorCount: 7,
    bestPrice: 8900,
    avgPrice: 9180,
    worstPrice: 9600,
    priceChange24h: -3.2,
    priceChangePct: -3.2,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per box',
  },
  {
    id: 'ups-apc-650va',
    name: 'APC UPS 650VA',
    category: 'Power',
    subcategory: 'UPS Systems',
    description: 'APC Back-UPS 650VA/360W with AVR (Automatic Voltage Regulation). Includes USB monitoring port.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/APC_Back-UPS_ES525.jpg/960px-APC_Back-UPS_ES525.jpg',
    tags: ['650VA', '360W', 'AVR', 'USB monitoring', 'APC', 'BX650CI'],
    vendorCount: 5,
    bestPrice: 6400,
    avgPrice: 6720,
    worstPrice: 7200,
    priceChange24h: 1.8,
    priceChangePct: 1.8,
    lastUpdated: new Date().toISOString(),
    isFavorited: true,
    hasAlert: false,
    unit: 'per unit',
  },
  {
    id: 'switch-cisco-sg110',
    name: 'Cisco SG110-8 Switch',
    category: 'Networking',
    subcategory: 'Switches',
    description: '8-port Gigabit unmanaged switch with plug-and-play setup. Ideal for small office networking.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Ethernet_switch_Atlantis_A02-F5P_5_ports_backend.jpg/960px-Ethernet_switch_Atlantis_A02-F5P_5_ports_backend.jpg',
    tags: ['8-port', 'Gigabit', 'Unmanaged', 'Cisco', 'SG110-08'],
    vendorCount: 4,
    bestPrice: 12400,
    avgPrice: 12900,
    worstPrice: 13500,
    priceChange24h: -1.1,
    priceChangePct: -1.1,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per unit',
  },
  {
    id: 'monitor-dell-p2422h',
    name: 'Dell P2422H 24" Monitor',
    category: 'IT & Computers',
    subcategory: 'Monitors',
    description: 'Full HD IPS display with USB-C, HDMI, and DisplayPort. Pivot and height-adjustable stand.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/LED_Screen_Computer.jpg',
    tags: ['24 inch', 'FHD 1080p', 'IPS Panel', 'USB-C', 'Pivot stand', 'Dell'],
    vendorCount: 5,
    bestPrice: 24800,
    avgPrice: 25600,
    worstPrice: 27000,
    priceChange24h: 2.3,
    priceChangePct: 2.3,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per unit',
  },
  {
    id: 'keyboard-mx-keys',
    name: 'Logitech MX Keys',
    category: 'Office Supplies',
    subcategory: 'Keyboards',
    description: 'Wireless backlit keyboard with multi-device support (up to 3 devices). Smart illumination.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Keyboard_Cherry_Stream_Wireless%2C_German_layout_%28c._2020%29.jpg/960px-Keyboard_Cherry_Stream_Wireless%2C_German_layout_%28c._2020%29.jpg',
    tags: ['Wireless', 'Backlit', 'Multi-device', 'USB-C', 'Logitech'],
    vendorCount: 6,
    bestPrice: 9200,
    avgPrice: 9480,
    worstPrice: 10200,
    priceChange24h: 0.4,
    priceChangePct: 0.4,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per unit',
  },
  {
    id: 'ssd-samsung-870',
    name: 'Samsung 870 EVO 1TB',
    category: 'IT & Computers',
    subcategory: 'Storage',
    description: '2.5" SATA SSD with sequential read speeds up to 560 MB/s. 5-year warranty.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Samsung_980_PRO_PCIe_4.0_NVMe_SSD_1TB-top_PNr%C2%B00915.jpg/960px-Samsung_980_PRO_PCIe_4.0_NVMe_SSD_1TB-top_PNr%C2%B00915.jpg',
    tags: ['1TB', '2.5" SATA', '560 MB/s', 'Samsung', '5yr warranty'],
    vendorCount: 5,
    bestPrice: 11800,
    avgPrice: 12200,
    worstPrice: 13000,
    priceChange24h: -2.7,
    priceChangePct: -2.7,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per unit',
  },
  {
    id: 'paper-a4-80gsm',
    name: 'A4 Paper Ream (80gsm)',
    category: 'Stationery',
    subcategory: 'Paper',
    description: 'Premium A4 copy paper, 80gsm, 500 sheets per ream. Acid-free for long-lasting documents.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/15_reams_of_paper_stacked_on_the_floor.jpg/960px-15_reams_of_paper_stacked_on_the_floor.jpg',
    tags: ['A4', '80gsm', '500 sheets', 'Acid-free'],
    vendorCount: 12,
    bestPrice: 450,
    avgPrice: 480,
    worstPrice: 550,
    priceChange24h: -0.9,
    priceChangePct: -0.9,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per ream',
  },
  {
    id: 'mouse-logitech-m720',
    name: 'Logitech M720 Triathlon',
    category: 'Office Supplies',
    subcategory: 'Mice',
    description: 'Multi-device wireless mouse for power users. Works across up to 3 computers with Easy-Switch.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/A_wireless_computer_mouse.jpg/960px-A_wireless_computer_mouse.jpg',
    tags: ['Wireless', 'Multi-device', 'Easy-Switch', 'Logitech'],
    vendorCount: 7,
    bestPrice: 7800,
    avgPrice: 8100,
    worstPrice: 8600,
    priceChange24h: 1.2,
    priceChangePct: 1.2,
    lastUpdated: new Date().toISOString(),
    isFavorited: false,
    hasAlert: false,
    unit: 'per unit',
  },
];

// ─── Vendors ──────────────────────────────────────────────────────────────────

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 'ms-computers',
    name: 'MS Computers & Wholesalers',
    initials: 'MS',
    category: 'IT hardware & peripherals',
    description: 'Leading IT products distributor and wholesaler. Specializes in supplying high-quality technology solutions to corporate clients and institutions.',
    location: 'Nairobi CBD',
    area: 'CBD',
    rating: 4.7,
    reviewCount: 312,
    badge: 'Verified',
    productCount: 84,
    phone: '+254 20 222 3344',
    email: 'sales@mscomputers.co.ke',
    whatsapp: '+254 722 100 200',
    openingHours: 'Mon–Fri 8:00–18:00, Sat 9:00–16:00',
    isVerified: true,
    isFavorited: true,
    colorHex: '#1a3a5c',
    logoUrl: 'https://api.dicebear.com/9.x/rings/png?seed=MS&backgroundColor=1a3a5c',
    joinedDate: '2023-02-01',
  },
  {
    id: 'gadgetronix',
    name: 'Gadgetronix Kenya Ltd',
    initials: 'GK',
    category: 'Computers, networking, CCTV',
    description: 'One-stop shop for computers, networking equipment, CCTV systems, and IT accessories. Corporate and retail.',
    location: 'Kilimani, Nairobi',
    area: 'Kilimani',
    rating: 4.5,
    reviewCount: 189,
    badge: 'Verified',
    productCount: 67,
    phone: '+254 20 555 7788',
    email: 'info@gadgetronix.co.ke',
    whatsapp: '+254 733 400 500',
    openingHours: 'Mon–Sat 8:30–17:30',
    isVerified: true,
    isFavorited: false,
    colorHex: '#2d5a3d',
    logoUrl: 'https://api.dicebear.com/9.x/rings/png?seed=GK&backgroundColor=2d5a3d',
    joinedDate: '2023-05-15',
  },
  {
    id: 'dove-computers',
    name: 'Dove Computers Kenya',
    initials: 'DC',
    category: 'HP authorized dealer',
    description: 'Authorized HP dealer in Kenya. Genuine HP products at competitive prices. Corporate procurement specialists.',
    location: 'Westlands, Nairobi',
    area: 'Westlands',
    rating: 4.8,
    reviewCount: 421,
    badge: 'Premium',
    productCount: 52,
    phone: '+254 20 444 5566',
    email: 'corporate@dovecomputers.co.ke',
    whatsapp: '+254 700 800 900',
    openingHours: 'Mon–Fri 8:00–17:00, Sat 9:00–13:00',
    isVerified: true,
    isFavorited: false,
    colorHex: '#5a2d2d',
    logoUrl: 'https://api.dicebear.com/9.x/rings/png?seed=DC&backgroundColor=5a2d2d',
    joinedDate: '2022-11-01',
  },
  {
    id: 'sai-office',
    name: 'Sai Office Supplies',
    initials: 'SO',
    category: 'Stationery, IT peripherals',
    description: 'Part of Ramco Group. Leading wholesaler and distributor of stationery, IT peripherals, and office essentials.',
    location: 'Westlands, Nairobi',
    area: 'Westlands',
    rating: 4.3,
    reviewCount: 234,
    badge: 'Trusted',
    productCount: 143,
    phone: '+254 20 666 7890',
    email: 'orders@saioffice.co.ke',
    openingHours: 'Mon–Fri 7:30–17:30, Sat 8:00–15:00',
    isVerified: true,
    isFavorited: false,
    colorHex: '#4a3d1a',
    logoUrl: 'https://api.dicebear.com/9.x/rings/png?seed=SO&backgroundColor=4a3d1a',
    joinedDate: '2023-01-20',
  },
  {
    id: 'vector-digital',
    name: 'Vector Digital Kenya',
    initials: 'VD',
    category: 'IT products, EMEA distributor',
    description: 'Reliable IT products supplier within EMEA. Partners with multinational technology companies for consistent supply.',
    location: 'Upper Hill, Nairobi',
    area: 'Upper Hill',
    rating: 4.6,
    reviewCount: 156,
    badge: 'Verified',
    productCount: 38,
    phone: '+254 20 888 9900',
    email: 'kenya@vectordigital.com',
    website: 'https://vds.co.ke',
    openingHours: 'Mon–Fri 8:00–17:00',
    isVerified: true,
    isFavorited: false,
    colorHex: '#2d3a5a',
    logoUrl: 'https://api.dicebear.com/9.x/rings/png?seed=VD&backgroundColor=2d3a5a',
    joinedDate: '2023-08-10',
  },
  {
    id: 'almiria',
    name: 'Almiria Solutions',
    initials: 'AL',
    category: 'Printers, scanners, consumables',
    description: 'Authorized dealer for HP, Epson, Brother, Kyocera, and Canon. Printer sales, service, and consumables supply.',
    location: 'Ngara, Nairobi',
    area: 'Ngara',
    rating: 4.4,
    reviewCount: 98,
    badge: 'New',
    productCount: 29,
    phone: '+254 20 333 4455',
    email: 'sales@almiria.co.ke',
    openingHours: 'Mon–Fri 8:30–17:30, Sat 9:00–14:00',
    isVerified: false,
    isFavorited: false,
    colorHex: '#3a2d5a',
    logoUrl: 'https://api.dicebear.com/9.x/rings/png?seed=AL&backgroundColor=3a2d5a',
    joinedDate: '2024-01-05',
  },
];

// ─── Vendor listings per product ──────────────────────────────────────────────

export const MOCK_VENDOR_LISTINGS: Record<string, VendorListing[]> = {
  'laptop-hp-840': [
    { vendorId: 'dove-computers', vendorName: 'Dove Computers', vendorLocation: 'Westlands', vendorBadge: 'Premium', price: 78500, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString(), contactPhone: '+254 20 444 5566' },
    { vendorId: 'ms-computers', vendorName: 'MS Computers', vendorLocation: 'CBD', vendorBadge: 'Verified', price: 80000, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'gadgetronix', vendorName: 'Gadgetronix Kenya', vendorLocation: 'Kilimani', vendorBadge: 'Verified', price: 81500, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'vector-digital', vendorName: 'Vector Digital', vendorLocation: 'Upper Hill', vendorBadge: 'Verified', price: 84200, inStock: false, minOrderQty: 2, updatedAt: new Date().toISOString(), notes: 'Lead time: 3 business days' },
  ],
  'toner-cf230a': [
    { vendorId: 'almiria', vendorName: 'Almiria Solutions', vendorLocation: 'Ngara', vendorBadge: 'New', price: 3200, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'sai-office', vendorName: 'Sai Office Supplies', vendorLocation: 'Westlands', vendorBadge: 'Trusted', price: 3400, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'ms-computers', vendorName: 'MS Computers', vendorLocation: 'CBD', vendorBadge: 'Verified', price: 3450, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'dove-computers', vendorName: 'Dove Computers', vendorLocation: 'Westlands', vendorBadge: 'Premium', price: 3600, inStock: true, minOrderQty: 3, updatedAt: new Date().toISOString() },
  ],
  'cable-cat6-305m': [
    { vendorId: 'gadgetronix', vendorName: 'Gadgetronix Kenya', vendorLocation: 'Kilimani', vendorBadge: 'Verified', price: 8900, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'ms-computers', vendorName: 'MS Computers', vendorLocation: 'CBD', vendorBadge: 'Verified', price: 9100, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'vector-digital', vendorName: 'Vector Digital', vendorLocation: 'Upper Hill', vendorBadge: 'Verified', price: 9400, inStock: true, minOrderQty: 2, updatedAt: new Date().toISOString() },
  ],
  'ups-apc-650va': [
    { vendorId: 'vector-digital', vendorName: 'Vector Digital', vendorLocation: 'Upper Hill', vendorBadge: 'Verified', price: 6400, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'ms-computers', vendorName: 'MS Computers', vendorLocation: 'CBD', vendorBadge: 'Verified', price: 6600, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
    { vendorId: 'dove-computers', vendorName: 'Dove Computers', vendorLocation: 'Westlands', vendorBadge: 'Premium', price: 6800, inStock: true, minOrderQty: 1, updatedAt: new Date().toISOString() },
  ],
};

// ─── Price trends (30-day) ────────────────────────────────────────────────────

function generateTrend(endPrice: number, days: number, volatility: number) {
  const points = [];
  let price = endPrice * (1 + (Math.random() * volatility * 2 - volatility));
  for (let i = days; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);
    price = price + (endPrice - price) * 0.1 + (Math.random() - 0.5) * endPrice * 0.01;
    points.push({
      date: date.toISOString().split('T')[0],
      avgPrice: Math.round(price),
      minPrice: Math.round(price * 0.96),
    });
  }
  return points;
}

export const MOCK_TRENDS: Record<string, PriceTrend> = {
  'laptop-hp-840': {
    productId: 'laptop-hp-840',
    period: '30d',
    dataPoints: generateTrend(78500, 30, 0.04),
  },
  'toner-cf230a': {
    productId: 'toner-cf230a',
    period: '30d',
    dataPoints: generateTrend(3200, 30, 0.08),
  },
  'cable-cat6-305m': {
    productId: 'cable-cat6-305m',
    period: '30d',
    dataPoints: generateTrend(8900, 30, 0.03),
  },
  'ups-apc-650va': {
    productId: 'ups-apc-650va',
    period: '30d',
    dataPoints: generateTrend(6400, 30, 0.05),
  },
  'switch-cisco-sg110': {
    productId: 'switch-cisco-sg110',
    period: '30d',
    dataPoints: generateTrend(12400, 30, 0.04),
  },
  'monitor-dell-p2422h': {
    productId: 'monitor-dell-p2422h',
    period: '30d',
    dataPoints: generateTrend(24800, 30, 0.03),
  },
  'keyboard-mx-keys': {
    productId: 'keyboard-mx-keys',
    period: '30d',
    dataPoints: generateTrend(9200, 30, 0.02),
  },
  'ssd-samsung-870': {
    productId: 'ssd-samsung-870',
    period: '30d',
    dataPoints: generateTrend(11800, 30, 0.06),
  },
  'paper-a4-80gsm': {
    productId: 'paper-a4-80gsm',
    period: '30d',
    dataPoints: generateTrend(450, 30, 0.05),
  },
  'mouse-logitech-m720': {
    productId: 'mouse-logitech-m720',
    period: '30d',
    dataPoints: generateTrend(7800, 30, 0.03),
  },
};

// Compact price history for inline card sparklines — last N points from the
// full 30-day trend, computed once at module load (not per-render).
export function getSparklinePoints(productId: string, points = 14): number[] {
  const trend = MOCK_TRENDS[productId];
  if (!trend) return [];
  return trend.dataPoints.slice(-points).map(p => p.avgPrice);
}

// ─── Ticker ───────────────────────────────────────────────────────────────────

export const MOCK_TICKER: TickerItem[] = MOCK_PRODUCTS.slice(0, 8).map(p => ({
  productId: p.id,
  name: p.name.length > 22 ? p.name.slice(0, 22) + '…' : p.name,
  price: p.bestPrice,
  change: p.priceChange24h,
  isUp: p.priceChange24h >= 0,
}));

// ─── Market Summary ───────────────────────────────────────────────────────────

export const MOCK_MARKET_SUMMARY: MarketSummary = {
  totalProducts: 284,
  activeVendors: 47,
  avgPriceMovement: 2.4,
  topDrops: MOCK_PRODUCTS.filter(p => p.priceChange24h < 0).sort((a, b) => a.priceChange24h - b.priceChange24h).slice(0, 3),
  topGains: MOCK_PRODUCTS.filter(p => p.priceChange24h > 0).sort((a, b) => b.priceChange24h - a.priceChange24h).slice(0, 3),
  recentUpdates: MOCK_PRODUCTS.slice(0, 5),
};

// ─── Alerts ───────────────────────────────────────────────────────────────────

export const MOCK_ALERTS: PriceAlert[] = [
  {
    id: 'alert-1',
    productId: 'toner-cf230a',
    productName: 'HP CF230A Toner',
    targetPrice: 3000,
    currentPrice: 3200,
    direction: 'below',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'alert-2',
    productId: 'laptop-hp-840',
    productName: 'HP EliteBook 840 G8',
    targetPrice: 75000,
    currentPrice: 78500,
    direction: 'below',
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

// ─── Notifications ────────────────────────────────────────────────────────────

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'price_drop',
    title: 'Price dropped — CF230A Toner',
    body: 'Almiria Solutions lowered their price to KES 3,200. Down 8% from last week.',
    productId: 'toner-cf230a',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'new_vendor',
    title: 'New vendor in your area',
    body: 'Almiria Solutions has joined SokoPrice and listed 29 products.',
    vendorId: 'almiria',
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'price_drop',
    title: 'CAT6 Cable price dipped',
    body: 'Gadgetronix Kenya: KES 8,900 per box — 3.2% lower than yesterday.',
    productId: 'cable-cat6-305m',
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];
